href: /blog/translation
acherno: 'Ачерно'
webSite: Официален сайт
youtube: YouTube канал
facebook: Facebook страница
blog: Блог за дизайн
interior: Интериор
projectsPrivate: (Жилищен) интериор
projectsPublic: (Обществен) интериор
designProjects: (Интериорни) проекти
designStyle: Стил
furniture: Обзавеждане
likes: Впечатления
views: Разглеждания
finished: (Завършени) интериори
more: Виж още (интериори)
bathroom: Баня и тоалетна
nursery: Детска стая
kitchen: Кухня и трапезария
bedroom: Спалня
livingroom: Хол и всекидневна
modern: Модерни интериори
modernclassic: Модерна класика
classic: Класически интериори
private: Жилищни интериори
public: Обществени интериори
randomPosts: (Интересни) предложения
featuredPosts: (Избрани) публикации
ideas: Идеи (за обзавежане)
impressions: (Направени) впечатления
from: от
back: Назад
instagram: (Instagram) вдъхновение